# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: workflow_dispatch

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build ODataQueryBuilder/ODataQueryBuilder.csproj --configuration $BUILD_CONFIG --no-restore
      
    - name: Test
      if: ${{ false }}
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-build --verbosity normal
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: /home/runner/work/odata-query-builder/**/*.nupkg
      
    - name: Publish
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
        dotnet nuget push **/*.nupkg --source github --skip-duplicate
